### ISSUE TITLE
CP-11586: Build 24003 has some problems...

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/QuickGraph#21]
*From unknown CodePlex user on Saturday, 08 November 2008 23:31:44*

Sample Code:
For Each Vertex As PointVertexType In Graph.Vertices 'Iterate Graph
            Select Case Graph.AdjacentEdges(Vertex).Count
                Case 1 ' dead end
                Case 2 ' line
                Case Is >= 3 : Vertex.IsIntersection = True
            End Select
        Next
 
2nd lines fails with:
    System.TypeLoadException occurred
    Message="GenericArguments[1], 'TVertex', on 'QuickGraph.IGraph`2[TVertex,TEdge]' violates the constraint    of type parameter 'TEdge'."
  Source="QuickGraph"
  TypeName=""
  StackTrace:
       at QuickGraph.UndirectedGraph`2.AdjacentEdges(TVertex v)
       at TigerViewer.DeadEndProcessor.Process(Object State) in C:\Projects\Rt1Viewer\DeadEnds.vb:line 97
  InnerException:

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Sunday, 09 November 2008 07:10:49*

Debug and Release configurations should work. DebugContracts, which has runtime checks enabled, has issue.

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Sunday, 09 November 2008 18:57:39*

Getting build errors on release:
Error	2	The command ""C:\Program Files (x86)\Microsoft\Contracts\Bin\ccrefgen.exe" "obj\Release\QuickGraph.decl.dll" "/out:.\bin\Release\QuickGraph.Contracts.dll"" exited with code -532459699.	C:\Program Files (x86)\Microsoft\Contracts\Microsoft.CodeContracts.targets	125	7	QuickGraph


Specifically:  "AsmMeta has encountered an error and needs to close"
                Send Error report to Microsoft

Same problem with Debug Build:
Error	2	The command ""C:\Program Files (x86)\Microsoft\Contracts\Bin\ccrefgen.exe" "obj\Debug\QuickGraph.decl.dll" "/out:.\bin\Debug\QuickGraph.Contracts.dll"" exited with code -532459699.	C:\Program Files (x86)\Microsoft\Contracts\Microsoft.CodeContracts.targets	125	7	QuickGraph


In both cases QuickGraph.Dll appears in the proper folder..

The last few days the build of the latest released in clean directory
would file on signing the assembly..

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Sunday, 09 November 2008 23:43:31*

contracts are disabled, things should be good again.

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Monday, 10 November 2008 21:07:33*
