### ISSUE TITLE
CP-12474: BidirectionalGraph addEdge() error

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/QuickGraph#46]
*From unknown CodePlex user on Monday, 26 January 2009 11:35:09*

I create two vertices and try to add a single edge, but get this error.
 
Code:
this.graph = new BidirectionalGraph<Vertex<int>, Edge<Vertex<int>>>(true);
this.edge = new Edge<Vertex<int>>(new Vertex<int>(0, 0), new Vertex<int>(0,0));
...
...
this.graph.addEdge(edge);
 
Error:
[01:29:01] System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at QuickGraph.BidirectionalGraph`2.AddEdge(TEdge e)
 
QuickGraph v 3.2.40122

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Monday, 26 January 2009 19:36:48*

You need to add the vertex *instances* to the graph before adding the edge. Or use AddVerticesAndEdge. If this still does not work, re-open the bug and attach a repro program. Thanks,
Peli

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Monday, 26 January 2009 19:37:32*

**Comment by fubar-coder** [comment]
*Form unknown CodePlex user on Wednesday, 30 September 2009 02:18:50*

I ran into the same problem.

My question: is this a general requirement on the contents of graphs?
(I.e. the invariant that all nodes that are endpoints of edges in a graph are themselves nodes in that graph.)

If it is, it can be stated in contracts on the mutators (or even on all members),
and/or a specific exception can be thrown at runtime.

It's important for me to know because I frequently have graphs with "dangling" edges - e.g. hierarchical graphs with edges between different subgraphs (GraphML supports this).  Knowing this invariant helps me decide how to represent such situations in QuickGraph.
